mysite/api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'questions', views.QuestionViewSet)
router.register(r'choices', views.ChoiceViewSet)
urlpatterns = [
	path('', include(router.urls)),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("", views.index, name="index"),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

mysite/polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import views
from .views.signup import signup, signup_submit
from .views.login import login, login_submit, logout
from .views.detail import detail
from .views.vote import vote
from .views.create_question import create_question, create_question_submit
from .views.search import search
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', signup, name='signup'),
    path('signup_submit/', signup_submit, name='signup_submit'),
    path('login/', login, name='login'),
    path('login_submit/', login_submit, name='login_submit'),
    path('logout/', logout, name='logout'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),
    path('<int:question_id>/clear_votes/', views._clear_votes, name='_clear_votes'),
    path('create_question/', create_question, name='create_question'),
    path('create_question_submit/', create_question_submit, name='create_question_submit'),
    path('search/', search, name='search'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	answered_by = models.ManyToManyField(User, editable=True, blank=True, related_name='answered_by')
	raw_id_fields = ('answered_by',)
	author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	def __str__(self):
			return self.question_text
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

mysite/polls/views/create_question.py
from datetime import datetime, timezone
from django.http import HttpResponse, HttpResponseRedirect
from ..models import Choice, Question
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.contrib import auth

def create_question(request):
    """
    Form view for creating questions.
    """
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    return render(request, 'polls/create_question.html')

def create_question_submit(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    
    question = Question(question_text=request.POST['question_text'], author=request.user, pub_date=datetime.now())
    question.save()
    
    for field in request.POST:
        if field.startswith('choice'):
            choice = Choice(question=question, choice_text=request.POST[field])
            choice.save()
            
    return HttpResponseRedirect(reverse('polls:index'))

mysite/polls/views/detail.py
from ..models import Choice, Question
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

def detail(request, question_id):
    """
    A view that displays a single question and its choices.
    """
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    print(question.answered_by.all())
    
    if question.answered_by.filter(pk=request.user.pk).exists():
        print("User has already voted")
        
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    return render(request, 'polls/detail.html', {'question': question})

mysite/polls/views/login.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

def login(request):
	return render(request, 'polls/login.html')

def login_submit(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return HttpResponseRedirect(reverse('index'))
    else:
        HttpResponse('<h1>Invalid username or password</h1>')

def logout(request):
	auth_logout(request)
	return HttpResponseRedirect(reverse('index'))

mysite/polls/views/search.py
from django.shortcuts import get_object_or_404, render
from ..models import Question
def search(request):
    if request.method == 'POST':
        search_term = request.POST['search_term']
        
        questions = Question.objects.filter(question_text__icontains=search_term)
        # questions = Question.objects.filter(question_text__contains=search_term)
        context = {
            "search_term": search_term,
            "questions": questions,
        }
        
        return render(request, 'polls/search.html', context)
    
    return render(request, 'polls/search.html')

mysite/polls/views/signup.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.models import User


def signup(request):
    return render(request, 'polls/signup.html')

def signup_submit(request):
    # print the request body
    print(request.POST["username"])
    print(request.POST["email"])
    print(request.POST["password"])
    User.objects.create_user(request.POST["username"], request.POST["email"], request.POST["password"])
    
    return HttpResponseRedirect(reverse('polls:index'))

mysite/polls/views/views.py
from django.http import HttpResponse, HttpResponseRedirect
from ..models import Choice, Question
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.contrib import auth

def index(request):
    """
    Home of the polls app. It shows a list of all the polls.
    """
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list, 'user_name': user.username}
    return render(request, 'polls/index.html', context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def _clear_votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answered_by.clear()
    print("Votes cleared")
    print(question.answered_by.all())
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/views/vote.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
from ..models import Choice, Question
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

def vote(request, question_id):
    """
    Not a view, but a backend route for voting.
    """
    question = get_object_or_404(Question, pk=question_id)
    if question.answered_by.filter(pk=request.user.pk).exists():
        print("User has already voted")
        print(question.answered_by.all())
        
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        question.answered_by.add(request.user)
        selected_choice.votes += 1
        selected_choice.save()
        print(question.answered_by.all())
        
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
{# djlint:off H030,H031 #}
<html lang="en">
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <title>
            Polls:
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        <div id="header-container">
            <div id="header">
                <div id="header-user-name">
                    {% block header %}
                        {% if user.is_authenticated and user.username %}<p>Hello, {{ user.username }}</p>{% endif %}
                    {% endblock header %}
                </div>
                <a href="{% url 'polls:index' %}">Home</a>
                <form class="search-form" action="{% url 'polls:search' %}" method="post">
                    {% csrf_token %}
                    <input type="search" name="search_term" placeholder="Search" />
                    <button type="submit" class="search-button" value="Search">Search</button>
                </form>
                <a href="{% url 'polls:create_question' %}">Create Poll</a>
                <div id="header-logout-container">
                    {% block logout %}
                        {% if user.is_authenticated %}
                            <a href="{% url 'polls:logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'polls:login' %}">Login</a>
                            <a href="{% url 'polls:signup' %}" class="signup-link">Signup</a>
                        {% endif %}
                    {% endblock logout %}
                    {% comment %} <a href="{% url 'polls:signup' %}">Signup</a> {% endcomment %}
                </div>
            </div>
        </div>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>
{# djlint:on #}

mysite/polls/templates/polls/create_question.html
{% extends "polls/base.html" %}
{% block title %}
    Create Poll
{% endblock title %}
{% block content %}
    <form action="{% url 'polls:create_question_submit' %}"
          method="post"
          id="choices">
        {% csrf_token %}
        <input type="text" name="question_text" placeholder="Question Text" />
        <button type="button"
                value="Add Choice"
                onclick="addChoice()"
                class="add-button">Add Choice</button>
        <button type="submit" id="submit" class="submit-button">Submit</button>
    </form>
    <script>
		var choice_count = 0;
		function addChoice() {
			choice_count++;
			var new_choice = document.createElement("input");
			new_choice.type = "text";
			new_choice.name = "choice_" + choice_count;
			new_choice.placeholder = "Choice " + choice_count;
			submit = document.getElementById("submit");
			document.getElementById("choices").insertBefore(new_choice, submit);
		}
    </script>
{% endblock content %}

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block title %}
    {% if question.question_text %}
        {{ question.question_text }}
    {% else %}
        Question
    {% endif %}
{% endblock title %}
{% block content %}
    <a href="{% url 'polls:index' %}">back</a>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <h1>{{ question.question_text }}</h1>
        {% if error_message %}
            <p>
                <strong>{{ error_message }}</strong>
            </p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio"
                   name="choice"
                   id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br />
        {% endfor %}
        <button type="submit" value="Vote" class="submit-button">Vote</button>
    </form>
{% endblock content %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block title %}
    Index
{% endblock title %}
{% block content %}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <script src="" async defer></script>
{% endblock content %}

mysite/polls/templates/polls/login.html
{% extends "polls/base.html" %}
{% block content %}
    <form action="{% url 'polls:login_submit' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="username" />
        <input type="password" name="password" id="password" placeholder="password" />
        <button type="submit" name="submit" class="submit-button" value="login">Login</button>
    </form>
{% endblock content %}

mysite/polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block content %}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    {% comment %} <a href="{% url 'polls:_clear_votes' question.id %}">__clear_votes</a> {% endcomment %}
    {% comment %} <a href="{% url 'polls:detail' question.id %}">Vote again?</a> {% endcomment %}
{% endblock content %}

mysite/polls/templates/polls/search.html
{% extends "polls/base.html" %}
{% block title %}
    Search
{% endblock title %}
{% block content %}
    <h1>
        Search for...
        {% if search_term %}{{ search_term }}{% endif %}
    </h1>
    {% for question in questions %}
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        <br />
    {% endfor %}
{% endblock content %}

mysite/polls/templates/polls/signup.html
{% extends "polls/base.html" %}
{% block content %}
    <form action="{% url 'polls:signup_submit' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="Username" />
        <input type="text" name="email" id="email" placeholder="E-mail" />
        <input type="password" name="password" id="password" placeholder="Password" />
        <input type="password"
               name="password2"
               id="password2"
               placeholder="Repeat your password"/>
        <button type="submit" id="submit" class="submit-button" value="Signup">Signup</button>
    </form>
    <script>
	username = document.getElementById('username');
	email = document.getElementById('email');
	password1 = document.getElementById('password');
	password2 = document.getElementById('password2');
	submit = document.getElementById('submit');
	submit.disabled = true;
	emailRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])+\.(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

	isFormValid = function() {
		if (password1.value != password2.value || password1.value == '' || password2.value == '' || username.value == '' || !emailRegex.test(email.value)) {
			return false;
		}
		else {
			return true;
		}
	}

	username.onkeyup = function() {
		if (isFormValid()) {
			submit.disabled = false;
		}
		else {
			submit.disabled = true;
		}
	}

	email.onkeyup = function() {
		if (isFormValid()) {
			submit.disabled = false;
		}
		else {
			submit.disabled = true;
		}
	}

	password1.addEventListener('keyup', function(){
		if(isFormValid()) {
			submit.disabled = false;
		}
		else{
			submit.disabled = true;
		}
	} );

	password2.addEventListener('keyup', function(){
		if(isFormValid()) {
			submit.disabled = false;
		}
		else{
			submit.disabled = true;
		}
	} );
    </script>
{% endblock content %}